name: Cargo Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable", "beta", "nightly"]
        crypto: ["ring", "aws-lc-rs", "ring,aws-lc-rs", ""]
        tokio: ["tokio", "tokio,axum", ""]
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --features ${{ matrix.crypto }},${{ matrix.tokio }}
      - run: cargo test --verbose --features ${{ matrix.crypto }},${{ matrix.tokio }}
